kronostechnologies/design-elements

- packages/react/src/components/modal/modal-dialog.test.tsx.snap
- packages/react/src/components/modal/modal.test.tsx.snap
- packages/react/src/components/modal/modal.tsx
- packages/react/src/themes/theme.ts
- packages/react/src/themes/tokens.ts
Update la couleur de l'overlay des modales qui est maintenant `rgba(0, 0, 0, 0.75)`.
[Maquettes CPanel](https://app.abstract.com/projects/f39bb9a0-d2db-11e8-b657-63d973464341/branches/master/commits/latest/files/8e822eb0-bc0e-440a-b9bd-d23e4c77c00d/layers/FE415DBA-6319-4464-9F05-2B9DE56E3D2D?collectionId=ecf361b5-ff5a-43b9-8127-80e5a291a1ba&collectionLayerId=7b70a200-7dbc-4327-9581-6569aa4018cb&mode=design&selected=root-4FDB52F1-D0A2-4C36-947C-46B4FEBDA6C3)
[Maquettes Centralize](https://app.abstract.com/projects/fde2bf20-a028-4108-8678-0960c9adac2f/branches/e9d04caa-7b50-4da1-87a0-147986c5ea89/commits/latest/files/5f68a04e-999d-4807-b21f-993f689ea406/layers/4D5C37B1-D84F-4E6D-9C83-8FBE2B89BBDA?collectionId=463e5c17-5cf5-40da-a5c8-61e1d19b6c3f&collectionLayerId=71462e4c-cef7-4171-a8f4-78e8 …
> chore(Modal): update overlay background-color

- .github/workflows/react.yml
Change `>` pour `>>` dans le `echo` de npm publish en espérant fixer la publication sur npm.
> ci: change '>' to '>>' in npm publish

- packages/react/src/components/menu-button/menu-button.test.tsx
- packages/react/src/components/menu-button/menu-button.tsx
- packages/storybook/stories/menu-button.stories.tsx
Cette PR ajoute les features suivantes au component MenuButton qui sont nécessaires pour une story CPanel2:
- Permettre de changer le label du bouton avec la prop `label`
- Permettre d'utiliser un IconButton via la prop `iconName`
Je ne sais pas vraiment comment on a fait pour manquer le fait qu'on n'avait pas encore la possibilité de changer le label sur MenuButton, mais bon ça va être là après cette PR 😄
> feat(MenuButton): add iconName and label props

- packages/react/src/components/card/card.test.tsx
- packages/react/src/components/card/card.test.tsx.snap
- packages/react/src/components/card/card.tsx
- packages/react/src/components/datepicker/datepicker.test.tsx.snap
- packages/react/src/components/datepicker/datepicker.tsx
- packages/react/src/components/tabs/tab-button.tsx
- packages/react/src/components/tabs/tab-panel.tsx
- packages/react/src/components/tabs/tabs.test.tsx
- packages/react/src/components/tabs/tabs.test.tsx.snap
- packages/react/src/components/tabs/tabs.tsx
- packages/react/src/styles/_variables.scss
- packages/react/src/styles/body.scss
- packages/storybook/stories/tabs.stories.tsx
Cette PR update le visuel du component Tabs avec les nouvelles maquettes. Les nouvelles tabs comportent un style par défaut et un style global. Un peu de refactor a été fait et j'ai ajouté la prop `noPadding` sur le component Card.
DS-573
> DS-573 chore(Tabs): update styles

- packages/react/src/components/table/sort-button-icon.test.tsx.snap
- packages/react/src/components/table/sort-button-icon.tsx
Ce PR met les icônes de sorting du component Table dans le bon ordre, car ils étaient inversés. J'ai vérrifié avec @maboilard et c'est bien le visuel qu'on veut.
[Exemple maquettes CPanel2](https://app.abstract.com/projects/f39bb9a0-d2db-11e8-b657-63d973464341/branches/master/commits/latest/files/8e822eb0-bc0e-440a-b9bd-d23e4c77c00d/layers/D1BD0356-F2B3-4A77-A7CE-6757A2B0EDE5?collectionId=084f6dc7-7b05-458e-a2b8-ac054250c5de&collectionLayerId=f5aaa9aa-704e-41b0-a62f-e816dbec0da5)
> refactor(Table): inverse sort icons

- packages/react/src/components/buttons/button.tsx
- packages/react/src/components/buttons/icon-button.tsx
- packages/react/src/components/menu-button/menu-button.tsx
- packages/react/src/components/nav-menu-button/nav-menu-button.tsx
Cette PR ajoute la prop `autofocus` aux boutons qui permet de diriger le focus sur un élément au premier load de la page. C'est une propriété HTML de base, donc j'ai fait des tests fonctionnels sur chacuns des components ciblés mais sans plus.
> DS-42 feat: add autofocus prop to buttons

- packages/react/src/components/datepicker/datepicker.test.tsx.snap
- packages/react/src/components/datepicker/datepicker.tsx
Le CSS de react-datepicker avait ajouté un `margin-bottom: -8px` dans la nouvelle version.
> fix(DatePicker): day names appear over the first row of the calendar

- packages/react/src/components/badge/badge.test.tsx
- packages/react/src/components/badge/badge.test.tsx.snap
- packages/react/src/components/badge/badge.tsx
- packages/react/src/index.ts
- packages/storybook/stories/badge.stories.tsx
DS-618
Ajout d'un composant pour afficher un badge sur une icône (ou tout autre élément).
- Affichage avec ou sans valeur (cercle ou point)
- Possibilité de configurer la valeur maximale (pour l'affichage du +)
- Option pour animer le badge (bounce)
> feat(Badge): add badge component

- packages/react/src/components/listbox/listbox.test.tsx.snap
- packages/react/src/components/listbox/listbox.tsx
- packages/react/src/components/select/select.test.tsx.snap
[DS-625](https://jira.equisoft.com/browse/DS-625)
Lorsqu'on a un checkbox en dessous d'un list box, le checkbox apparaît par dessus la liste d'éléments. Augmenter le z-index du list box règle le problème.
> feat(ListBox): increase list box z-index

- packages/react/src/components/badge/badge.test.tsx
- packages/react/src/components/badge/badge.tsx
DS-624
Ajout des props `offsetX` et `offsetY` pour permettre de positionner plus précisément le badge (par exemple dans le cas où l'élément qu'il accompagne a un padding et qu'on veut que le badge soit plus près). Ces nouvelles props acceptent une valeur numérique en px, motivé par le fait que nos variables de spacing soient aussi en px.
> feat(Badge): add offset props

- packages/react/src/components/select/select.test.tsx
- packages/react/src/components/select/select.tsx
[DS-626](https://jira.equisoft.com/browse/DS-626)
Problème : Lorsqu'un élément est déjà sélectionné, on ne peut pas voir les autres options dans le dropdown si on est en mode searchable. Les options devraient seulement être filtrées lorsqu'on est en mode "recherche" (en train d'écrire quelque chose dans le input). 
Comment reproduire : 
1. Utilisez la recherche pour sélectionner un élément du dropdown. Le Select doit être en mode searchable (prop searchable à true). 
2. Sélectionnez un élément du dropdown
3. Quand on essaies de sélectionner un élément à nouveau, la liste est filtré sur l'élément sélectionné précédemment.
> feat(Select): fix select options when a value is already selected

- packages/react/src/components/menu-button/menu-button.tsx
- packages/storybook/stories/menu-button.stories.tsx
Dans `/plan` nous avons besoin que les MenuButtons supportent un style Inverted
> feat(MenuButton): support inverted props

- packages/react/src/components/menu-button/menu-button.test.tsx
- packages/react/src/components/menu-button/menu-button.tsx
Le MenuButton causait un `scrollTo(0)` lorsqu'il était clické, on déterminé que le problème semblait venir du `react-popper-tooltip`, qui n'est pas nécessaire au bon fonctionnement de ce component,
> fix(MenuButton): react-popper-tooltip removed, cause weird scroll

- index.html
Le path de la page d'introduction a changé depuis l'update à Storybook 7. En redirigeant simplement vers la version _latest_ sans spécifier de path, on laisse Storybook ouvrir la première page disponible.
> chore: Redirect to latest without specific path

- packages/react/src/components/bento-menu-button/bento-menu-button.test.tsx.snap
- packages/react/src/components/breadcrumb/breadcrumb.test.tsx.snap
- packages/react/src/components/dropdown-menu-button/dropdown-menu-button.test.tsx.snap
- packages/react/src/components/dropdown-menu/dropdown-menu.test.tsx.snap
- packages/react/src/components/external-link/external-link.test.tsx.snap
- packages/react/src/components/external-link/external-link.tsx
- packages/react/src/components/route-link/route-link.test.tsx.snap
- packages/react/src/components/route-link/route-link.tsx
- packages/react/src/components/route-link/styles/styled-link.tsx
DS-714
L'élément `<a>` généré par les composants `<RouteLink>` et `<ExternalLink>` contiennent un attribut `type` erroné. Cet attribut existe dans la spec mais devrait contenir un mimetype s'il est utilisé. L'attribut en question a été retiré car il n'était pas utilisé.
De plus, certains attributs sont désuets depuis la migration à react-router v6 (`activeClassName`).
Finalement, certaines déclarations de style étaient dupliquées dans plusieurs types de liens. Elles ont été ramenées dans le composant abstrait `<StyledLink>`.
**Tests fonctionnels**
- Tous les composants dont le snapshot a changé sont visuellement identiques dans le storybook
> refactor(Link): remove unused attributes and duplicated code

- packages/react/src/components/menu-button/menu-button.test.tsx
- packages/react/src/components/menu-button/menu-button.tsx
- packages/storybook/stories/menu-button.stories.tsx
Remove auto-focus from first menu item at the DS-level, as requested on [ABF-6488](https://jira.equisoft.com/browse/ABF-6488).
> fix(MenuButton): remove auto-focus from first menu item (ABF-6488)

- packages/react/src/components/modal/modal-dialog.test.tsx
- packages/react/src/components/modal/modal-dialog.tsx
- packages/storybook/stories/modal-dialog.stories.tsx
:link: [DS-708](https://jira.equisoft.com/browse/DS-708)
Ajout d'un type: `ModalType = 'information-modal' | 'action-modal' | 'destructive-modal';`
- information-modal: Modale à un bouton. Pour le nouveau variant `Information`.
- Action-modal: Modale à deux boutons. Variant `Par défaut`.
- Destructive-modal: Modale par défaut à deux boutons. Le bouton principale est de type `destructive`. Pour le nouveau vairant `Alert`.
Ajout au Storybook des deux nouvelles variantes de modales.
Stories:
Information Modal:
Destructive Modal:
> DS-708: Adds destructive & information modal variant

- packages/react/src/components/modal/modal-dialog.test.tsx
- packages/react/src/components/modal/modal-dialog.tsx
- packages/storybook/stories/modal-dialog.stories.tsx
[DS-708](https://jira.equisoft.com/browse/DS-708)
Suite à quelques révisions, un renommage de `ModalType` pour `DialogType` était nécessaire et plus approprié.
Ainsi, un renommage du type `destructive` à `alert` était nécessaire et plus approprié pour l'uniformité.
> DS-708: fix(ModalDialog): dialogType naming

- packages/react/src/components/tooltip/tooltip.test.tsx.snap
- packages/react/src/components/tooltip/tooltip.tsx
> feat(Tooltip): adjust style to fit doc

- .yarnrc.yml
- yarn.lock
Met Yarn PnP en mode strict, ce qui enlève les erreurs [MODULE_NOT_FOUND] lors de la compilation et des tests. Les problèmes de dépendances de Storybook ont pu être contournées via les packageExtensions.
Par contre, c'était nécessaire de spécifier une version majeure pour éviter que les nouvelles dépendances pointent vers react 18. Il faudra penser à mettre ça à jour quand on changera de version majeure.
> chore(yarn): use pnp strict mode

- packages/react/test/setup.ts
Empêche l'affichage de nombreuses erreurs à propos de `useLayoutEffect` lors de l'exécution des tests.
Le output des test sera pas mal plus utilisable après ça!
> chore: fix useLayoutEffect errors in tests

- packages/react/src/components/text-input/text-input.test.tsx
- packages/react/src/components/text-input/text-input.tsx
- packages/storybook/stories/text-input.stories.tsx
[DS-822](https://jira.equisoft.com/browse/DS-822)
Jusqu'à maintenant, TextInput affichait le message d'erreur quand:
- le champ est vide avec l'attribut `required`.
- la valeur du champ ne respecte pas le pattern de l'attribut `pattern`.
Ajout d'un attribut `valid` pour contrôler l'affichage du message d'erreur pour une validation personnalisée.
> feat(TextInput): add valid prop to TextInput

- packages/react/src/components/feedbacks/invalid-field.tsx
- packages/react/src/components/password-creation-input/password-rule.tsx
The icon used for the error message was not the correct one; the triangle has been replaced with an octagon.
> fix(inputs): remplace error icon

- packages/react/src/components/date-picker/date-picker.tsx
[DS-889](https://jira.equisoft.com/browse/DS-889)
Auparavant, lorsqu'un utilisateur ouvrait le calendrier d'un composant Datepicker puis cliquait sur le bouton d'un autre composant Datepicker, les deux calendriers restaient ouverts simultanément. Cette PR corrige ce comportement afin qu'un seul calendrier puisse être ouvert à la fois.
Ajout d'un événement personnalisé pour fermer les autres instances de Datepicker lors de l'ouverture d'un nouveau.
À l'aide d'un listener d'événements sur le document permettant d'écouter cet événement et fermer le Datepicker actuellement ouvert si nécessaire.
> fix(date-picker): ensure one datepicker is open

- packages/storybook/.storybook/preview.tsx
While Storybook use the same order as defined in the Props interface, but sometimes it's not possible when your interface extends or has intersected types. So this config will make Storybook to always sort the arguments.
**Before**
**After**
> feat(Storybook): sort arguments alphabetically

- packages/react/src/components/table/table.tsx
DS-927
The previous syntax works only with TypeScript 5+, also "(A & B)[]" is a better syntax.
> fix(Table): typing error on props data

- packages/react/src/components/toast/toast-container.test.tsx.snap
- packages/react/src/components/toast/toast-container.tsx
- Ajouter un `role="img"` sur le `svg` de l'icône pour une question d'a11y
- remplacer le type du bouton "dismiss" de `type="submit"` à `type="button"`.
> fix(toast): ajouter role sur svg et remplacer type button

- packages/react/src/components/text-input/text-input.test.tsx
- packages/react/src/components/text-input/text-input.tsx
- packages/storybook/stories/text-input.stories.tsx
En ce moment, la prop valid dans TextInput ne fonctionne pas correctement quand on trigger blur, le message d'erreur disparaît et on doit reloader la section pour qu'il revienne.
> fix(TextInput): make sure that blur event doesn't break error message.

- packages/react/src/components/date-picker/calendar-header.tsx
- packages/react/src/components/date-picker/date-picker.test.tsx.snap
- packages/react/src/components/date-picker/utils/datepicker-utils.ts
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.tsx
- packages/react/src/components/field-container/field-container.test.tsx.snap
- packages/react/src/components/field-container/field-container.tsx
- packages/react/src/components/label/label.tsx
- packages/react/src/components/listbox/listbox.test.tsx.snap
- packages/react/src/components/listbox/listbox.tsx
- packages/react/src/components/stepper-input/stepper-input.test.tsx.snap
- packages/react/src/components/text-area/text-area.test.tsx.snap
- packages/react/src/components/text-area/text-area.tsx
- packages/react/src/components/text-input/text-input.test.tsx.snap
- packages/react/src/components/text-input/text-input.tsx
- packages/react/src/hooks/use-aria-conditional-ids.ts
- packages/react/src/hooks/use-click-outside.ts
- packages/react/src/hooks/use-list-search.ts
- packages/react/src/i18n/translations.ts
- packages/react/src/index.ts
- packages/react/src/utils/string.test.ts
- packages/react/src/utils/string.ts
- packages/storybook/stories/dropdown-list.stories.tsx
DS-247
The search functionality is being moved to the upcoming combobox/autocomplete components. Thus, the text input in the dropdown was replaced by a `<div>` and a hidden input to hold the value when the component is used in a form. It now acts as a simple `<select>`.
The remaining code was also refactored to use the new listbox and to improve its general shape.
Note: I did not include the multi-select feature in this PR. It should be done in a separate story.
> feat(Dropdown)!: update behavior and use updated listbox

- packages/react/src/components/date-picker/date-picker.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.tsx
- packages/react/src/components/listbox/listbox.test.tsx.snap
- packages/react/src/components/listbox/listbox.tsx
- packages/storybook/stories/listbox.stories.tsx
DS-954
Le textbox du dropdown perdait le focus quand on cliquait sur une option _disabled_. En écoutant `onClick` même sur ces options, on peut rétablir manuellement le focus.
De plus, on retire certains handlers sur la listbox lorsque qu'elle n'est pas focusable.
> fix(Dropdown): keep textbox focused when clicking on disabled options

- packages/react/src/components/dropdown-menu/list-items/nav-item.tsx
- packages/react/src/components/external-link/external-link.tsx
- packages/react/src/components/user-profile/user-profile.test.tsx
- packages/react/src/components/user-profile/user-profile.test.tsx.snap
- packages/react/src/components/user-profile/user-profile.tsx
- packages/storybook/stories/user-profile.stories.tsx
Ref: https://jira.equisoft.com/browse/DS-919
- Le props target n'était pas passé au nav-item du component user-profile.
- Ajout de la propriété `isExternalLink` qui permet de render un lien externe avec l'icône correspondante:
> fix(user-profile,nav-item): pass target to html-link and use external-link

- packages/react/src/components/date-picker/date-picker.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx.snap
- packages/react/src/components/feedbacks/invalid-field.test.tsx.snap
- packages/react/src/components/feedbacks/invalid-field.tsx
- packages/react/src/components/field-container/field-container.test.tsx.snap
- packages/react/src/components/field-container/field-container.tsx
- packages/react/src/components/numeric-input/numeric-input.test.tsx
- packages/react/src/components/numeric-input/numeric-input.test.tsx.snap
- packages/react/src/components/numeric-input/use-numeric-input.tsx
- packages/react/src/components/password-input/password-input.test.tsx.snap
- packages/react/src/components/stepper-input/stepper-input.test.tsx.snap
- packages/storybook/stories/numeric-input.stories.tsx
- yarn.lock
Afficher les messages d'erreurs au debut lorsqu'on a un value ou defaultValue qui n'est pas valide, a l'exception pour un string vide on ne valide pas le required.
J'ai aussi fixe un bug en fesant mes tests: 
- data-testid pour les message d'erreurs dans FieldContainer n'etait pas render.
> fix(numeric-input): show error message initially

- packages/react/src/components/pagination/pagination.test.tsx
- packages/react/src/components/pagination/pagination.test.tsx.snap
- packages/react/src/components/pagination/pagination.tsx
- packages/storybook/stories/pagination.stories.tsx
https://equisoft.atlassian.net/browse/DS-965
Dans la composante de Pagination, retirer l'assignation d'un nombre de page précis à afficher (prop `totalPages`) et le remplacer par le nombre de résultats à afficher par page. 
Cela a pour effet de dynamiquement calculer le nombre de pages à afficher, en fonction de la valeur d'entrée de la prop `resultsPerPage`, et du nombre total de résultats.
> fix(Pagination): replace totalPages with resultsPerPage

- packages/react/src/components/date-picker/date-picker.tsx
https://equisoft.atlassian.net/browse/DS-990
Le callback `handleCalendarButtonMouseDown` du component `CalendarButton` change le state open/close du calendrier et causait des problèmes avec les callbacks `onCalendarOpen/onCalendarClose` du component `DatePicker`
La solution est de caller ces callbacks dans le `handleCalendarButtonMouseDown` pour éviter de les caller aux moments où ils devraient pas.
Avant (clic pour ouverture du calendrier):
Après (idem)
> fix(datepicker): call calendar open/close events in calendarbutton on mousedown callback

- packages/storybook/package.json
- yarn.lock
- It has limited Node versions support (require to install quite a few build tools to compile it on the dev machine, which add complexity to local setup (especially on Windows).
- It's deprecated.
> chore(packages): replace node-sass by sass

- packages/react/src/hooks/use-dev-console.ts
- packages/react/src/index.ts
- packages/react/src/utils/dev-console.ts
DS-1092
Wrapper pour l'objet global `console` qui permet de logger seulement en dev. Rien n'est affiché dans la console dans le build pour la production ni dans les tests.
Usage:
```ts
import { devConsole } from '../utils/dev-console';
devConsole.warn('WARNING (only for devs)');
```
Évidemment, pour logger en tout temps, `console.log` et autres continuent de fonctionner tel quel.
> feat(Console): provide a mean to log only in dev

- packages/react/src/components/global-header/global-header.tsx
- packages/react/src/components/skip-link/skip-link.test.tsx.snap
- packages/react/src/components/skip-link/skip-link.tsx
- packages/react/src/themes/tokens/component/global-header-tokens.ts
- packages/react/src/themes/tokens/component/skip-link-tokens.ts
Le skip-link n'avait pas de couleur background prédéfinie autre qu'une valeur `inherit` du `defaultButtonStyles` mais sa couleur était définie dans le composant `global-header`.
J'ai ajouté un `background-color` directement dans le composant et supprimé ce qui était dans le global-header.
https://equisoft.atlassian.net/browse/DS-1077
> fix(skip-link): add bg-color

- packages/react/src/components/combobox/combobox.test.tsx
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx.snap
- packages/react/src/components/listbox/listbox.test.tsx
- packages/react/src/components/listbox/listbox.test.tsx.snap
- packages/react/src/components/listbox/listbox.tsx
DS-1093
Marquer les props de styling comme transitives pour éviter qu'elles ne se retrouvent dans le DOM.
> chore(Listbox): mark styling props as transient

- packages/storybook/.storybook/main.ts
- packages/storybook/package.json
- yarn.lock
DS-1095
Ajouter le add-on “controls” dans le storybook pour permettre aux utilisateurs d’explorer les différentes configurations tout en limitant le nombre de stories à écrire à la base.
Note: Aucun contrôle n'est configuré pour l'instant, ils seront ajoutés dans le cadre de la refonte de la doc présentement en cours.
> chore(Storybook): add controls add-on

- packages/react/src/components/global-banner/global-banner.test.tsx.snap
- packages/react/src/components/global-banner/global-banner.tsx
[DS-1106](https://equisoft.atlassian.net/browse/DS-1106)
- Titre de la banner sur une ligne et texte sur une autre ligne
- ajouter un `aria-labelledby="[id du title]` sur la `section` qui wrap le content
[DS-1106]: https://equisoft.atlassian.net/browse/DS-1106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(global banner): title on single line

- packages/react/src/components/table/table-header.tsx
- packages/react/src/components/table/table-row.tsx
- packages/react/src/components/table/table.test.tsx
- packages/react/src/components/table/table.test.tsx.snap
- packages/react/src/components/table/utils/table-utils.ts
- packages/storybook/stories/table.stories.tsx
Ref: https://equisoft.atlassian.net/browse/DS-933
> feat(table,storybook): add header grouping to table header

- packages/react/src/components/date-picker/calendar-header.tsx
- packages/react/src/components/date-picker/date-picker.test.tsx.snap
- packages/react/src/components/date-picker/date-picker.tsx
[DS-802](https://equisoft.atlassian.net/browse/DS-802)
Ici on vient update les boutons de month navigation dans le calendar du datepicker pour qu’ils ne trigger pas de form submission. J'en ai profité pour ajouter la prop `required` qui m'a également premis de tester le comportement désiré.
[DS-802]: https://equisoft.atlassian.net/browse/DS-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(datepicker): fix navigation buttons form submission

- packages/react/src/components/buttons/button.test.tsx
- packages/react/src/components/buttons/button.test.tsx.snap
- packages/react/src/components/buttons/button.tsx
- packages/storybook/stories/button.stories.tsx
https://equisoft.atlassian.net/browse/DS-1076
> feat(button): allow icons to be placed left and right of button

- packages/react/src/components/dropdown-list/dropdown-list.tsx
https://equisoft.atlassian.net/browse/DS-1158
Lors de l'implémentation du `dropdown-list` dans le CRM, on a trouvé un bug qui fait planter le component si la valeur de la prop `value` n'est pas comprise dans l'array d'options. 
Normalement, il devrait simplement afficher aucune option, et non planter.
Facilement reproductible dans le Storybook:
```
export const WithoutSelectedOptions: Story = () => (
<DropdownList
data-testid="blip-bloop"
options={[]}
value={'test'}
/>
);
```
> fix(dropdown-list): prevents error when explicit value is not in options

- packages/react/src/components/tag/tag.test.tsx.snap
- packages/react/src/components/tag/tag.tsx
- packages/react/src/i18n/translations.ts
https://equisoft.atlassian.net/browse/DS-1134
- Enlever l’attribut `aria-hidden="true"` du Icon button ‘delete’ de la variante ‘Removable’.
- La valeur de l’attribut aria-label devrait être: ‘Remove + tag + [Nom du tag]’.
- Remplacer l'élément `<span>` qui wrap le Tag par un élément `<div>`.
> fix(tag): fix a11y et arialabel

- packages/react/src/components/tabs/tabs.tsx
- packages/storybook/stories/tabs.stories.tsx
[DS-1155](https://equisoft.atlassian.net/browse/DS-1155)
Ici on vient ajouter l'option d'avoir un tab selectionné par défaut.
[DS-1155]: https://equisoft.atlassian.net/browse/DS-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(Tabs)!: add default selected tab option

- packages/react/src/components/date-picker/date-picker.test.tsx.snap
- packages/react/src/components/date-picker/date-picker.tsx
- packages/react/src/themes/tokens/alias-tokens.ts
- packages/react/src/themes/tokens/component/datepicker-tokens.ts
DS-1183
Fix pour le date picker, il y a eu une confusion avec le terme 'overlay'. Le "masque" (backdrop) aurait dû être noir 50% et non blanc.
Avant:
Après:
> fix(Datepicker): change backdrop color

- packages/react/src/components/global-banner/global-banner.tsx
DS-1189
Permettre un bouton d'action secondaire même dans les bannières de type 'alerte'.
> fix: allow secondary action in alert banner

- packages/react/src/components/modal/modal-dialog.test.tsx.snap
- packages/react/src/components/modal/modal-dialog.tsx
DS-1188
Lorsque la modal avait une icône avant le heading, le texte dans le _main content_ était aligné avec le début du heading. Maintenant, il est aligné avec l'icône.
> fix(ModalDialog): align text with icon

- packages/react/src/components/bento-menu-button/bento-menu-button.test.tsx.snap
- packages/react/src/components/buttons/abstract-button.tsx
- packages/react/src/components/buttons/button.test.tsx.snap
- packages/react/src/components/buttons/button.tsx
- packages/react/src/components/buttons/icon-button.test.tsx.snap
- packages/react/src/components/carousel/carousel.test.tsx.snap
- packages/react/src/components/combobox/combobox.test.tsx.snap
- packages/react/src/components/date-picker/date-picker.test.tsx.snap
- packages/react/src/components/disclosure/disclosure.test.tsx.snap
- packages/react/src/components/dropdown-menu-button/dropdown-menu-button.test.tsx.snap
- packages/react/src/components/dropdown-navigation/dropdown-navigation.test.tsx.snap
- packages/react/src/components/global-banner/global-banner.test.tsx.snap
- packages/react/src/components/global-header/global-header.test.tsx.snap
- packages/react/src/components/global-navigation/global-navigation.test.tsx.snap
- packages/react/src/components/modal/modal-dialog.test.tsx.snap
- packages/react/src/components/modal/modal.test.tsx.snap
- packages/react/src/components/password-input/password-input.test.tsx.snap
- packages/react/src/components/tabs/tabs.test.tsx.snap
- packages/react/src/components/tag/tag.test.tsx.snap
- packages/react/src/components/theme-wrapper/theme-wrapper.test.tsx.snap
- packages/react/src/components/toast/toast-container.test.tsx.snap
- packages/react/src/components/toggletip/toggletip.test.tsx.snap
- packages/react/src/components/user-profile/user-profile.test.tsx.snap
https://equisoft.atlassian.net/browse/DS-743
Remplacer l'attribut `disabled` pour l'attribut d'accessibilité `aria-disabled="true"`.
> fix(Button): replace disabled for a11y attribute aria-disabled

- packages/react/src/components/pagination/pagination.test.tsx.snap
- packages/react/src/components/pagination/pagination.tsx
Remplacer le `span` par un `div` vient fixer une failure de validation HTML:
`Element [h3] not allowed as child of element [span] in this context.`
> fix(Pagination): change span for div

- packages/react/src/components/modal/modal-dialog.tsx
Quick fix qui ajoute un attribut d'a11y `aria-hidden="true"` sur l'icône qui se trouve devant le heading.
> fix(Modal): icon add ariaHidden

- packages/react/src/components/date-picker/date-picker.tsx
DS-1205
**Description**
Après avoir _parsé_ la valeur entrée sans séparateurs, c'était seulement le "selectedDate" (la valeur sélectionné lorsqu'on ouvre le calendrier) et le onChange n'était jamais appelé.
Donc, aucune manière pour le parent du DatePicker de connaitre la date finale.
> fix(DatePicker): When entering a date without separators, valid date should call onChange

- packages/react/src/components/radio-button/radio-button.test.tsx.snap
- packages/react/src/components/radio-button/radio-button.tsx
- packages/react/src/themes/tokens/component/radio-button-group-tokens.ts
Quand on zoomait à 110%, le dot du radio button ne gardait pas ses proportions, il devenait un peu ovale, et il était décalé du centre.
J'ai remplacer le CSS qui formait le dot par un svg.
Avant:
Après:
J'ai également enlever un margin-top sur le container qui ne servait à rien
> fix(RadioButton): not centered when zoomed

- packages/react/src/components/icon/icon.tsx
- packages/react/src/components/spinner/spinner.test.tsx.snap
- packages/react/src/components/spinner/spinner.tsx
- packages/react/src/icons/enso.svg
Remplacer le `svg` pour le nouveau visuel + bouger l'animation dans le `svg` au lieu de le faire dans le CSS.
**Avant:**
**Après:**
> fix(Spinner): replace svg

- packages/react/src/components/money-input/money-input.test.tsx.snap
- packages/react/src/components/password-creation-input/password-creation-input.tsx
- packages/react/src/components/password-input/password-input.test.tsx.snap
- packages/react/src/components/password-input/password-input.tsx
- packages/react/src/components/text-input/text-input.test.tsx
- packages/react/src/components/text-input/text-input.test.tsx.snap
- packages/react/src/components/text-input/text-input.tsx
- packages/react/src/themes/tokens/component/text-input-tokens.ts
- packages/storybook/stories/text-input.mdx
- packages/storybook/stories/text-input.stories.tsx
JIRA: https://equisoft.atlassian.net/browse/DS-1140
- Possibilité d'ajouter un _adornment_.
L'adornement peut être un `Icon` ou du `text`.
- Possible d'ajouter _l'adornment_ au début ou la fin du `TextInput`.
- Lorsqu'on click sur _l'adornement_ le `TextInput` est `focus`.
> feat(TextInput): ajout adornment (DS-1140)

- packages/react/src/components/segmented-control/segmented-control.test.tsx
- packages/react/src/components/segmented-control/segmented-control.test.tsx.snap
- packages/react/src/components/segmented-control/segmented-control.tsx
- packages/react/src/themes/tokens/alias-tokens.ts
- packages/react/src/themes/tokens/component/segmented-control-tokens.ts
- packages/storybook/stories/segmented-control.mdx
- packages/storybook/stories/segmented-control.stories.tsx
DS-1231
- Modifier le style du composant
- Ajout option d'avoir des icônes ou non
- Ajout option d'avoir tjrs un bouton de pressed
- Modification dans les tokens du composant (Breaking change)
> feat(SegmentedControl)!: new Style and add icon

- packages/react/src/components/money-input/money-input.test.tsx.snap
- packages/react/src/components/money-input/money-input.tsx
[DS-710](https://equisoft.atlassian.net/browse/DS-710)
Ici on vient faire quelques ajustements à notre composante `MoneyInput`
- Retrait du placeholder
- Alignement du texte à gauche par défaut
- Ajout d'une propriété permettant de modifier l'alignement du texte
- Exposition de la propriété `noMargin` du `FieldContainer`
Voici un warning soulevé par le DOM Validator:
```
Warning: The inputmode attribute is not supported in all browsers. Please be sure to test, and consider using a polyfill.
[From line 1, column 382; to line 1, column 588](https://validator.w3.org/nu/#l1c588)
...<input aria-describedby="430c793c-a80a-4ee2-1009-c2ec277e3722_hint" data-testid="some-data-testid" i…793c-a80a-4ee2-1009-c2ec277e3722" inputmode="numeric" type="text" class="sc-fecduv biaUDu" value="">...
``` …
> fix(MoneyInput): update styling and behavior

- packages/react/src/components/bento-menu-button/bento-menu-button.test.tsx.snap
- packages/react/src/components/breadcrumb/breadcrumb.test.tsx.snap
- packages/react/src/components/dropdown-menu-button/dropdown-menu-button.test.tsx.snap
- packages/react/src/components/dropdown-menu/dropdown-menu.test.tsx.snap
- packages/react/src/components/error-summary/error-summary.test.tsx.snap
- packages/react/src/components/external-link/external-link.test.tsx.snap
- packages/react/src/components/link/link.test.tsx.snap
- packages/react/src/components/route-link/route-link.test.tsx.snap
- packages/react/src/components/user-profile/user-profile.test.tsx.snap
- packages/react/src/themes/tokens/alias-tokens.ts
Actuellement, l'état visited des Link conserve une couleur différente de l'état par défaut. Cela cause des problèmes visuels car l'application ne vide pas l'historique de navigation, et les liens déjà visités restent dans cet état même lorsque l'utilisateur revient à une nouvelle session. Nous avons décidé de garder le même style pour l'état visited que celui par défaut.
https://equisoft.atlassian.net/browse/DS-1240
> fix(Token): replace visited color

- commitlint.config.mjs
La config de l'action inclut déjà tout ça, plus des scopes supplémentaires, comme `deps`
> ci: remove commitlint config override

- packages/react/src/components/checkbox-group/checkbox-group.test.tsx.snap
- packages/react/src/components/checkbox/checkbox.test.tsx.snap
- packages/react/src/components/checkbox/checkbox.tsx
- packages/react/src/components/table/table.test.tsx.snap
https://equisoft.atlassian.net/browse/DS-1261
Lorsque le label du checkbox est trop long et tombait sur 2 lignes, l'input était compressé.
> fix(Checkbox): prevent input compression with long text by adding flex-shrink

- packages/react/src/components/money-input/money-input.test.tsx.snap
- packages/react/src/components/money-input/money-input.tsx
- packages/react/src/components/numeric-input/numeric-input.test.tsx.snap
- packages/react/src/components/numeric-input/numeric-input.tsx
- packages/react/src/components/numeric-input/use-numeric-input.tsx
- packages/react/src/components/text-input/index.ts
- packages/react/src/components/text-input/text-input-classes.ts
- packages/react/src/components/text-input/text-input.test.tsx.snap
- packages/react/src/components/text-input/text-input.tsx
- packages/react/src/index.ts
- packages/react/src/utils/generate-component-classes.test.ts
- packages/react/src/utils/generate-component-classes.ts
Permet de contrôler la largeur de l'input en faisant 
```typescript
import { TextInput, textInputClasses } from '@equisoft/design-elements-react';
const SomeInput = styled(TextInput)`
.${textInputClasses.control} {
width: 80px;
}
`;
```
J'ai aussi ramené le numeric-input pour qu'il utilise le TextInput, et enlever un layer de div dans le MoneyInput.
> feat(MoneyInput,NumericInput,TextInput): expose CSS class to allow styling elements

- packages/react/src/components/radio-card-group/radio-card-group.test.tsx.snap
- packages/react/src/components/radio-card-group/styled-components.ts
Il y avait un problème visuel lorsque la card ne contenait qu’un titre sans texte en dessous. Le margin-bottom appliqué au titre augmentait la hauteur de la card, créant un espace visuel sous le titre qui n'était pas esthétique.
Un autre problème concernait la version verticale, où la propriété width: 100%; faisait dépasser les cards de l'espace alloué par le conteneur parent..
Changements effectués :
- Suppression du margin-bottom appliqué au titre pour éviter l'espacement excessif.
- Ajout d’un margin-top sur le contenu sous le titre, pour gérer l’espacement lorsqu’il est présent.
- Utilisation du pseudo-sélecteur :empty sur le contenu sous le titre afin de retirer le margin-top si le contenu est vide.
- Ajout de box-sizing: border-box; pour corriger la gestion de la largeur de la card. …
> fix(RadioCard) remove margin-bottom on heading

- packages/react/src/components/dropdown-list/dropdown-list.test.tsx.snap
- packages/react/src/components/listbox/listbox.test.tsx.snap
- packages/react/src/components/listbox/listbox.tsx
- packages/react/src/themes/tokens/component/listbox-tokens.ts
DS-1268
Il manquait la couleur background sur l'indicateur de l'option sélectionnée.
Avant:
Après:
> fix(Listbox): add bgcolor to  selected indicator

- packages/react/src/components/combobox/combobox.test.tsx.snap
- packages/react/src/components/date-picker/date-picker.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx.snap
- packages/react/src/components/feedbacks/invalid-field.test.tsx.snap
- packages/react/src/components/feedbacks/invalid-field.tsx
- packages/react/src/components/field-container/field-container.test.tsx.snap
- packages/react/src/components/numeric-input/numeric-input.test.tsx.snap
- packages/react/src/components/password-input/password-input.test.tsx.snap
- packages/react/src/components/stepper-input/stepper-input.test.tsx.snap
- packages/react/src/components/text-input/text-input.tsx
DS-1257
Les messages d'erreur dans le design system utilisaient des notifications automatiques pour les lecteurs d'écran (`aria-live` et `role="alert"`), mais avec le nouveau pattern de validation des formulaires, ces notifications ne sont plus nécessaires. De plus, l'attribut `aria-invalid` est maintenant ajouté dès que le champ est en erreur.
> fix(TextInput, InvalidField): remove a11y attribute error message + aria-invalid is automatic

- packages/react/src/components/table/table.tsx
- packages/storybook/stories/data-table.stories.tsx
https://equisoft.atlassian.net/browse/DS-1279
La fonction `onSelectedRowsChange` retournait pas les subRows lorsque la data-table était configurée en mode multiple + expandable. Ça retournait juste des copies de la row parente du grouping.
> feat(table): include returning subrows when on expandable multiple mode

- packages/webapp/src/browser/index.html
Ajoute le meta viewport pour prévenir un render `zoom-out` en mobile.
Réplique les changements fait ici: https://github.com/kronostechnologies/webapp-boilerplate/pull/878
> DS-1299 feat(Webapp): add meta viewport

- packages/react/src/components/link/link.test.tsx.snap
- packages/react/src/components/password-input/password-input.test.tsx.snap
- packages/react/src/components/tooltip/tooltip.test.tsx.snap
- packages/react/src/components/tooltip/tooltip.tsx
DS-1333
l'attribut `aria-describedby` était sur le span qui _wrap_ l'élément recevant le tooltip, il fallait le déplacer sur le children puisque c'est cette élément qui reçoit le focus et donc qui doit être décrit par la valeur de l'attribut.
> fix(Tooltip): move aria-describedby to children

- packages/react/src/components/link/link.test.tsx.snap
- packages/react/src/components/link/link.tsx
DS-1336
Ajouter un aria-label sur le lien lorsqu'il a seulement une icône.
> fix(Link): add aria-label icon only

- packages/react/src/components/dropdown-list/dropdown-list.test.tsx
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.tsx
https://equisoft.atlassian.net/browse/DS-1267
- The idea is to render the dropdown list in a different part of the DOM (like at the end of body) to prevent clipping issues caused by parent elements with overflow: hidden.
> feat(Dropdown): fix css z index issues with ReactPortal for Listbox

- packages/react/src/components/menu-button/menu-button.tsx
Le dropdown des options ne s'affiche pas au-dessus du bouton des autres menus.
> Add z-index to MenuButton component

- packages/react/src/components/buttons/abstract/types.ts
- packages/react/src/components/buttons/types.ts
- packages/react/src/components/tabs/tab-button.test.tsx
- packages/react/src/components/tabs/tab-button.tsx
- packages/react/src/components/tabs/tab-panel.tsx
- packages/react/src/components/tabs/tabs-classes.ts
- packages/react/src/components/tabs/tabs.test.tsx
- packages/react/src/components/tabs/tabs.test.tsx.snap
- packages/react/src/components/tabs/tabs.tsx
- packages/react/src/components/tabs/types.ts
- packages/react/src/themes/tokens/component/tab-tokens.ts
- packages/storybook/stories/tabs.mdx
- packages/storybook/stories/tabs.stories.tsx
DS-1294
**BREAKING:**
- retrait du boolean "global"
- changement aux tokens
---
Le style visuel du composant "Sectional Tab" a été modifié dans Figma. Le visuel est identique pour les deux variantes à l'exception de la taille des éléments. Le background, les couleurs et indicateurs sont les même. J'ai également ajouté l'option d'avoir ou non un `padding` avant les tabs du tablist. Ça va permettre de respecter certains visuels où les tabs arrive flush avec son _container_.
[EDIT]
J'ai dû modifier un peu l'ordre des éléments lorsqu'il y a un scroll et le bouton "add new Tab".
+ modifier tooltip sur le bouton Add new tabs pour qu'il ne soit affiché que lorsque le bouton est disabled
> fix(Tabs)!: update visuel global vs section

- packages/react/src/components/table/table-header.tsx
- packages/react/src/components/table/table-row.tsx
- packages/react/src/components/table/table.test.tsx
- packages/react/src/components/table/table.test.tsx.snap
- packages/react/src/components/table/table.tsx
- packages/react/src/components/table/utils/table-utils.ts
- packages/storybook/stories/data-table.stories.tsx
La PR #1153 enlevait le text-align sur tout, mais le browser centre par défaut le th. On veut que le default soit text-align left partout.
> fix(Table): apply default text-align left to header

- packages/legacy-tests/test/setup.ts
- packages/react/src/components/dropdown-list/dropdown-list.tsx
- packages/react/test/setup.ts
Ref: https://equisoft.atlassian.net/browse/LG-108
Depuis la version 9.8.1, le Dropdownlist ne s'ajuste pas lorsque l'on retire/ajout des éléments en multiselect. 
- Ajout d'un ResizeObserver au composant DropdownList pour surveiller les changements de taille du champ texte et mettre à jour la position de la liste déroulante en conséquence. 
Comportement actuel: 
Avec le fix: 
- https://github.com/kronostechnologies/design-elements/pull/1160
> fix(DropdownList): update listbox position when textbox height changes
