kronostechnologies/design-elements

- packages/react/src/components/sectional-banner/sectional-banner.tsx
- packages/react/src/components/status/status.test.tsx
- packages/react/src/components/status/status.tsx
- packages/react/src/index.ts
Cette PR exporte le type `StatusTypes` du component `Status` et le type `SectionalBannerTypes` du component `SectionalBanner` dans le package publique. Ce sera utilisé dans CPanel2.
> feat(Status): export StatusTypes and SectionalBannerTypes in public package

- packages/react/src/components/card/card.test.tsx.snap
- packages/react/src/components/card/card.tsx
Cette PR update le padding du component Card selon les nouvelles maquettes DS. J'ai confirmé avec @maboilard qu'on voulait bien apporter ce changement dans le DS.
[Maquette CPanel2 utilisant le DS](https://app.abstract.com/projects/f39bb9a0-d2db-11e8-b657-63d973464341/branches/81585b37-5fc3-45e1-94f6-430cc7cff4a0/commits/latest/files/8e822eb0-bc0e-440a-b9bd-d23e4c77c00d/layers/4B9FCF1A-763E-45B2-8965-BB21BD0397F7?collectionId=4dfa72eb-6c7a-4864-961a-04bc09201e0b&collectionLayerId=7b9cb7c6-e462-4aab-8cc0-0c2819941237&mode=build&selected=root-4B9FCF1A-763E-45B2-8965-BB21BD0397F7)
> chore(Card): update padding

- packages/react/src/components/modal/modal-dialog.test.tsx.snap
- packages/react/src/components/modal/modal.tsx
- packages/storybook/stories/modal-dialog.stories.mdx
- packages/storybook/stories/modal.stories.mdx
Cette PR update la padding du footer dans le component Modal. Dans les stories le contenu des modales ont été mis dans des `<span>` au lieu de des `<p>` pour éviter d'impacter le spacing.
> chore(Modal): update footer padding

- packages/react/src/components/datepicker/datepicker.test.tsx.snap
- packages/react/src/components/select/select.test.tsx
- packages/react/src/components/select/select.tsx
- packages/storybook/stories/select.stories.tsx
- yarn.lock
Petit bug trouvé lors de l'update du DS dans MFB.
> fix(Select): skipOption cannot be selected by default when value is controlled

- packages/react/src/components/bento-menu-button/bento-menu-button.test.tsx
- packages/react/src/components/bento-menu-button/bento-menu-button.test.tsx.snap
- packages/react/src/components/bento-menu-button/bento-menu-button.tsx
- packages/react/src/components/bento-menu-button/product-group.tsx
- packages/storybook/stories/bento-menu-button.stories.tsx
[DS-605](https://jira.equisoft.com/browse/DS-605)
Ces changements permettent d'ajouter des sections dynamiques pour les produits (nécessaire pour cpanel2).
> feat(BentoMenuButton): add productGroups props

- packages/react/src/components/tabs/tabs.test.tsx
- packages/react/src/components/tabs/tabs.tsx
- packages/storybook/stories/tabs.stories.tsx
[DS-610](https://jira.equisoft.com/browse/DS-610)
> feat(Tabs): make onBeforeUnload async

- packages/react/src/components/icon/icon.tsx
[DS-616](https://jira.equisoft.com/browse/DS-616)
> feat(Icon): add alert circle icon

- packages/react/src/components/feedbacks/invalid-field.tsx
- packages/react/src/components/field-container/field-container.tsx
- packages/react/src/components/icon/icon.tsx
- packages/react/src/components/money-input/money-input.test.tsx.snap
- packages/react/src/components/password-creation-input/password-creation-input.tsx
- packages/react/src/components/password-creation-input/password-creation.test.tsx
- packages/react/src/components/password-creation-input/password-rule.tsx
- packages/react/src/components/password-creation-input/password-strength-container.tsx
- packages/react/src/components/password-creation-input/password-strength-meter.tsx
- packages/react/src/components/password-creation-input/password-strength.enum.ts
- packages/react/src/components/password-creation-input/password-strength.test.ts
- packages/react/src/components/password-creation-input/password-strength.ts
- packages/react/src/components/password-creation-input/validation-condition.test.ts
- packages/react/src/components/password-creation-input/validation-condition.ts
- packages/react/src/components/search/search-input.test.tsx.snap
- packages/react/src/components/text-area/text-area.test.tsx.snap
- packages/react/src/components/text-input/styles/inputs.tsx
- packages/react/src/components/text-input/text-input.test.tsx.snap
- packages/react/src/components/text-input/text-input.tsx
- packages/react/src/i18n/translations.ts
- packages/react/src/index.ts
- packages/storybook/stories/password-creation-input.stories.tsx
[DS-153](https://jira.equisoft.com/browse/DS-153)
> feat(PasswordCreationInput): create password creation input component

- packages/react/src/components/phone-input/phone-input.test.tsx
- packages/react/src/components/phone-input/phone-input.tsx
- packages/react/src/components/radio-button-group/radio-button-group.test.tsx
- packages/react/src/components/radio-button-group/radio-button-group.test.tsx.snap
- packages/react/src/components/radio-button-group/radio-button-group.tsx
- packages/storybook/stories/phone-input.stories.tsx
- packages/storybook/stories/radio-button-group.stories.tsx
[DS-619](https://jira.equisoft.com/browse/DS-619)
Add controllable data-testid for RadioButtonGroup and PhoneInput.
> feat(RadioButtonGroup): add controllable data-testid

- packages/react/src/components/buttons/button.test.tsx.snap
- packages/react/src/components/buttons/button.tsx
- packages/react/src/components/modal/modal-dialog.test.tsx.snap
- packages/react/src/components/theme-wrapper/theme-wrapper.test.tsx.snap
[DS-623](https://jira.equisoft.com/browse/DS-623)
> feat(Button): set button default html type to button

- packages/react/src/components/lozenge/lozenge.test.tsx
- packages/react/src/components/lozenge/lozenge.test.tsx.snap
- packages/react/src/components/lozenge/lozenge.tsx
- packages/storybook/stories/lozenge.stories.tsx
[DS-633](https://jira.equisoft.com/browse/DS-633)
> feat(Lozenge): add lozenge types

- packages/react/src/components/radio-button-group/radio-button-group.test.tsx
- packages/react/src/components/radio-button-group/radio-button-group.test.tsx.snap
- packages/react/src/components/radio-button-group/radio-button-group.tsx
- packages/storybook/stories/radio-button-group.stories.tsx
[DS-635](https://jira.equisoft.com/browse/DS-635)
> feat(RadioButtonGroup): add tooltip to label

- packages/react/src/components/modal/modal-dialog.tsx
- packages/react/src/components/modal/modal.tsx
- packages/storybook/stories/modal-dialog.stories.mdx
- yarn.lock
This allows to insert the modal inside a shadow root
> feat(Modal): add parentSelector

- packages/react/src/components/sectional-banner/sectional-banner.test.tsx
- packages/react/src/components/sectional-banner/sectional-banner.test.tsx.snap
- packages/react/src/components/sectional-banner/sectional-banner.tsx
- packages/storybook/stories/sectional-banner.stories.tsx
[DS-637](https://jira.equisoft.com/browse/DS-637)
> feat(SectionalBanner): allow custom children type

- packages/react/src/components/shadow-wrapper/shadow-wrapper.tsx
Wrapped children in fragment as StyleSheetManager allows only one child
> fix(Shadow-wrapper): styleSheetManager allows only one child

- packages/react/package.json
- packages/react/src/components/breadcrumb/breadcrumb.test.tsx.snap
- packages/react/src/components/dropdown-menu/list-items/nav-item.tsx
- packages/react/src/components/global-navigation/global-navigation.tsx
- packages/react/src/components/nav-menu-button/nav-menu-button.test.tsx.snap
- packages/react/src/components/nav-menu/nav-menu-item.tsx
- packages/react/src/components/nav-menu/nav-menu-option.ts
- packages/react/src/components/nav-menu/nav-menu.test.tsx
- packages/react/src/components/nav-menu/nav-menu.tsx
- packages/react/src/components/route-link/route-link.tsx
- packages/react/src/components/route-link/styles/styled-link.tsx
- packages/storybook/package.json
- yarn.lock
[DS-649](https://jira.equisoft.com/browse/DS-649)
https://reactrouter.com/en/v6.3.0/upgrading/v5
> chore!: migrate to react router v6

- packages/react/src/components/tag/tag.tsx
- packages/storybook/stories/tag.stories.tsx
[DS-646](https://jira.equisoft.com/browse/DS-646)
> feat(Tag): add forwardRef to Tag component

- packages/react/src/components/datepicker/datepicker.test.tsx.snap
- packages/react/src/components/datepicker/datepicker.tsx
Ça vient de l'update de 4.1 à 4.8.
> fix(Datepicker): fix width on wrapper

- .tool-versions
- packages/react/webpack/webpack.config.common.js
La librairie était brisée dans le Storybook
> fix(Icon): fix duplicate ids yielding wrong render

- packages/react/src/components/breadcrumb/breadcrumb.test.tsx
- packages/react/src/components/breadcrumb/breadcrumb.test.tsx.snap
- packages/react/src/components/breadcrumb/breadcrumb.tsx
- packages/react/src/components/breadcrumb/use-breadcrum-layout-effect.test.tsx
- packages/react/src/components/breadcrumb/use-breadcrumb-layout-effect.tsx
- packages/react/src/components/breadcrumb/use-breadcrumb-overflow.tsx
- packages/react/src/components/breadcrumb/use-breadcrumb-routes.tsx
- packages/react/src/components/breadcrumb/use-breadcrump-overflow.test.ts
- packages/react/src/components/breadcrumb/use-breadcrump-routes.test.tsx
- packages/react/src/hooks/use-overflow.tsx
- packages/storybook/stories/breadcrumb.stories.tsx
> feat(Breadcrump): Make breadcrump more responsive 

- packages/react/src/components/chooser-card/styled-components.ts
- packages/react/src/themes/main.ts
- packages/react/src/themes/test-theme.ts
- packages/react/src/themes/theme.ts
Adjust theme properties to reflect information provided in Figma guide: https://www.figma.com/file/Rix8Euc5yoZTJHN6zoNA0K/R%C3%A9pertoire-de-th%C3%A8mes
No github issues; But an issue filed in JIRA: https://jira.equisoft.com/browse/ABF-5329
> feat(Theme): update theme properties to reflect new guide in Figma

- packages/react/src/components/toggletip/toggletip.test.tsx
- packages/react/src/components/toggletip/toggletip.test.tsx.snap
- packages/react/src/components/toggletip/toggletip.tsx
- packages/react/src/index.ts
- packages/react/src/styles/_variables.scss
- packages/storybook/stories/toggletip.stories.tsx
Based à partir des specs ici: https://www.notion.so/equisoft/Toggle-Tip-1ba74138a2634b5694aa039df165a296
> feat(Toggletip): Added Toggletip component

- packages/react/src/components/tooltip/tooltip.tsx
Address mouse flickering issue in tooltips, as raised in https://jira.equisoft.com/browse/ABF-5746.
> [ABF-5746] fix mouse flickering issue

- .github/workflows/react.yml
J'avais pas vu qu'il y avait 2 blocs 🤦‍♂️
> ci: fix Storybook deploy

- packages/react/src/components/menu-button/menu-button.tsx
- packages/storybook/stories/menu-button.stories.tsx
J'en aurais besoin dans le cadre des modifs de /plan
> feat(MenuButton): added onMenuVisibilityChange props

- packages/react/src/components/menu-button/menu-button.tsx
- packages/react/src/components/menu/menu.tsx
- packages/storybook/stories/menu-button.stories.tsx
Plus de détails et de contexte sur la carte https://jira.equisoft.com/browse/ABF-6740
> dev(MenuButton): add ability to choose menu display direction ABF-6740

- packages/react/src/components/tooltip/tooltip.test.tsx.snap
- packages/react/src/components/tooltip/tooltip.tsx
- packages/storybook/stories/tooltip.stories.tsx
> fix(Tooltip): visual regression

- packages/react/src/components/user-profile/user-profile.tsx
- packages/storybook/stories/user-profile.stories.tsx
[DS-893](https://jira.equisoft.com/browse/DS-893)
Ajoute le support du lozenge dans le UserProfile
> feat(UserProfile): add lozenge prop for nav items

- packages/react/src/components/buttons/abstract-button.tsx
- packages/react/src/components/tooltip/tooltip.test.tsx
- packages/react/src/components/tooltip/tooltip.tsx
- packages/storybook/stories/tooltip.stories.tsx
[DS-921](https://jira.equisoft.com/browse/DS-921)
> feat(IconButton): fix event propagation for buttons

- packages/react/src/components/table/sortable-column-heading.tsx
- packages/react/src/components/table/table.test.tsx.snap
> fix(Table): change sorting icon position

- .github/workflows/react.yml
[DS-788](https://jira.equisoft.com/browse/DS-788)
> ci: deploy storybook on pull_request event

- packages/react/src/components/date-picker/date-picker.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.tsx
- packages/storybook/stories/dropdown-list.stories.tsx
DS-957
Gestion de l'overflow dans le textbox du dropdown list.
> fix(Dropdown): prevent text overflow in dropdown-list textbox

- packages/react/src/components/menu/menu.test.tsx.snap
- packages/react/src/components/menu/menu.tsx
- packages/storybook/stories/menu-button.stories.tsx
https://www.figma.com/file/EIJItUlyeIymb2dfgeoQJp/Design-System%2C-Desktop?type=design&node-id=8484-25239&mode=design&t=UfSKkaOU2uF915j6-4
> Added disabled on MenuItem in MenuButton

- packages/react/src/components/table/sortable-column-heading.tsx
- packages/react/src/components/table/table-row.tsx
- packages/react/src/components/table/table.test.tsx.snap
- packages/react/src/components/table/table.tsx
- packages/storybook/stories/table.stories.tsx
Table component background color should inherit from parent container(th, tr, tfoot)
Tester que les différents modes de la table fonctionnent avec le background color du parent.
> fix(Table): table background color matches container background

- packages/react/src/components/table/table.tsx
- packages/storybook/stories/table.stories.tsx
[DS-923](https://equisoft.atlassian.net/browse/DS-923)
- Permettre de gerer manuellement le sorting avec un event callback.
- Ajouter un Story de la Table avec la Pagination.
[DS-923]: https://equisoft.atlassian.net/browse/DS-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(Table): manual sorting

- packages/react/src/components/buttons/abstract-button.tsx
- packages/react/src/components/buttons/button.test.tsx.snap
- packages/react/src/themes/tokens/component/button-tokens.ts
- packages/storybook/stories/buttons.stories.tsx
- packages/storybook/stories/icon-button.stories.tsx
Ajout d'une variante tertiaire destructive
https://equisoft.atlassian.net/browse/DS-1089
> feat(button): add variant

- packages/storybook/stories/3-changelog.mdx
> docs(storybook): add changelog

- package.json
- packages/storybook/.storybook/preview.tsx
- yarn.lock
DS-1095
Ajout de paramètres communs pour les contrôles: tri alphabétique des props et affichage 'expanded' pour inclure les colonnes de description et valeur par défaut dans le tableau des contrôles.
> chore(Storybook): add controls configuration

- packages/react/src/components/buttons/abstract-button.tsx
- packages/react/src/components/buttons/button.test.tsx
- packages/react/src/components/modal/modal-dialog.test.tsx
- packages/react/src/components/modal/modal-dialog.tsx
- packages/react/src/components/sectional-banner/sectional-banner.test.tsx
- packages/react/src/components/sectional-banner/sectional-banner.tsx
- packages/react/src/themes/tokens/component/button-tokens.ts
- packages/storybook/stories/1-getting-started.stories.tsx
- packages/storybook/stories/buttons.stories.tsx
- packages/storybook/stories/icon-button.stories.tsx
- packages/storybook/stories/menu-button.stories.tsx
- packages/storybook/stories/modal-dialog.stories.tsx
- packages/storybook/stories/toast.stories.tsx
Renommer la variante du bouton `destructive` avec un bg rouge pour `destructive-primary`
> feat(button)!: replace destructive for destructive-primary

- packages/storybook/stories/table.stories.tsx
Ref: https://equisoft.atlassian.net/browse/DS-929
> feat(storybook,table): add a case to table story for custom sortable row 

- packages/react/src/components/carousel/carousel.test.tsx.snap
- packages/react/src/components/carousel/carousel.tsx
- packages/react/src/themes/tokens/component/carousel-tokens.ts
DS-1083
- remplacer les btn de flèches par le composant IconButton du DS
> fix(carousel): remplacer btn par composant icon button

- packages/react/src/components/dropdown-list/dropdown-list.test.tsx
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.tsx
- packages/react/src/themes/tokens/component/dropdown-list-tokens.ts
- packages/storybook/stories/dropdown-list.mdx
- packages/storybook/stories/dropdown-list.stories.tsx
JIRA: https://equisoft.atlassian.net/browse/DS-1126
> feat(dropdown-list): DS-1126: add icon inside the Dropdown control

- packages/react/src/components/date-picker/calendar-header.tsx
- packages/react/src/components/date-picker/date-picker.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.tsx
- packages/react/src/components/listbox/listbox-option.ts
- packages/react/src/components/listbox/listbox.tsx
- packages/storybook/stories/dropdown-list.stories.tsx
- packages/storybook/stories/toggletip.stories.tsx
- packages/storybook/stories/tooltip.stories.tsx
Cherry-pick + fix pour publier #805 dans une version 6.3.0
> feat(dropdown-list): implements multiselect variant of dropdown-list

- packages/react/src/components/buttons/abstract-button.tsx
- packages/react/src/components/date-picker/date-picker.tsx
- packages/react/src/components/date-picker/utils/datepicker-utils.test.ts
- packages/react/src/components/date-picker/utils/datepicker-utils.ts
- packages/react/src/components/dropdown-list/dropdown-list.tsx
- packages/storybook/stories/buttons.stories.tsx
- packages/storybook/stories/icon-button.stories.tsx
> chore: cherry-picks for v6.4.0

- packages/react/src/theme.ts
> chore(theme): export theme customization

- packages/react/src/components/password-creation-input/password-creation-input.tsx
- packages/react/src/components/password-input/password-input.test.tsx.snap
- packages/react/src/components/password-input/password-input.tsx
https://equisoft.atlassian.net/browse/DS-1087
Remplacer le size de l'icône "Show password" dans les composants de password.
> fix(PasswordCreationInput,PasswordInput): change btn size

- packages/react/src/components/buttons/icon-button.tsx
- packages/react/src/components/toast/toast-container.test.tsx.snap
- packages/react/src/components/toggletip/toggletip.test.tsx.snap
- packages/react/src/components/toggletip/toggletip.tsx
- packages/storybook/stories/toggletip.mdx
- packages/storybook/stories/toggletip.stories.tsx
https://equisoft.atlassian.net/browse/DS-765
- Fix UI (border-radius, dimensions du pointer)
- ajout l'option d'avoir des icons buttons de différents size.
[Figma](https://www.figma.com/design/EIJItUlyeIymb2dfgeoQJp/Design-System%2C-Desktop?m=auto&node-id=4-53&t=G5pgBd0glPhgECoP-1)
> feat(Toggletip): add icon btn size + ui fixes

- packages/react/src/components/stepper-input/stepper-buttons.test.tsx
- packages/react/src/components/stepper-input/stepper-buttons.tsx
- packages/react/src/components/stepper-input/stepper-input.tsx
- packages/storybook/stories/stepper-input.mdx
JIRA: https://equisoft.atlassian.net/browse/DS-1156
Pour savoir si la vitesse de l'incrementation est adéquate. 
On peut augmenter la vitesse, mais selon moi le 200 ms entre chaque incrémentation me semble suffisant.
Dit moi ce que vous en penez.
> feat(StepperInput): incrémentation/décrémentation continue avec maintien du bouton de la souris (DS-1156)

- packages/webapp/src/browser/core/i18n/translations.ts
- packages/webapp/src/browser/modules/app/layout/AppLayout.component.tsx
- packages/webapp/src/browser/modules/app/layout/Header.component.tsx
- packages/webapp/src/browser/modules/app/layout/Menu.component.tsx
- packages/webapp/src/browser/modules/app/routes.ts
- packages/webapp/src/browser/modules/home/Home.component.tsx
- packages/webapp/src/browser/modules/users/Users.component.tsx
- packages/webapp/src/scripts/webpack/webpack.config.dev.js
[DS-1130](https://equisoft.atlassian.net/browse/DS-1130)
Ici on vient ajouter la liste d'utilisateurs à notre webapp!
[DS-1130]: https://equisoft.atlassian.net/browse/DS-1130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(webapp): adds users list page

- packages/react/src/components/table/table-header.tsx
- packages/react/src/components/table/table.test.tsx.snap
[DS-1186](https://equisoft.atlassian.net/browse/DS-1186)
...
[DS-1186]: https://equisoft.atlassian.net/browse/DS-1186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(table): sortable column headers focus state

- packages/react/src/components/segmented-control/segmented-control.test.tsx.snap
- packages/react/src/components/segmented-control/segmented-control.tsx
DS-1163
Le style hover du button n'était pas appliqué lorsque le bouton était en état _pressed_.
> fix(SegmentedControl): hover style on pressed btn

- packages/react/src/components/table/table-row.tsx
- packages/react/src/components/table/table.test.tsx.snap
- packages/react/src/components/table/table.tsx
- packages/react/src/themes/tokens/component/table-tokens.ts
- packages/storybook/stories/table.stories.tsx
DS-976
- changer la couleur background d'error
- Ajout d'un size large pour les row
> fix(Table): fix error background + add large size

- packages/webapp/src/browser/core/i18n/translations.ts
- packages/webapp/src/browser/modules/users/User.component.tsx
- packages/webapp/src/browser/modules/users/components/table/Table.component.tsx
- packages/webapp/src/browser/modules/users/components/table/cells/Delete.component.tsx
- packages/webapp/src/browser/modules/users/components/table/cells/index.ts
- packages/webapp/src/browser/modules/users/state/reducer.ts
- packages/webapp/src/browser/modules/users/types/user.ts
- packages/webapp/src/browser/modules/users/types/users-action.ts
- packages/webapp/src/browser/modules/users/utils/load-users.ts
[DS-1131](https://equisoft.atlassian.net/browse/DS-1131)
Ici on vient ajouter la data table d'utilisateurs
*Problème détecté: le focus sur les headers des columns lors d'une suppression ne se redirige pas sur le nom/lien du user de la row qui précédait celle supprimée.
[DS-1131]: https://equisoft.atlassian.net/browse/DS-1131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(webapp, users): adds delete action

- packages/react/src/components/combobox/combobox.tsx
- packages/react/src/hooks/use-list-select.ts
Ref: DS-1149
Préparer le composante ComboBox à pouvoir sélectionner plusieurs options. 
Mon objectif est d'éviter d'arriver avec une trop grosse PR qui pourrait altérer le comportement actuel du component sans que l'on s'en rende compte.
> chore(ComboBox): make combobox able to select and stored multiple options

- packages/react/src/components/radio-button/radio-input.tsx
- packages/react/src/components/radio-card-group/radio-card-group.test.tsx
- packages/react/src/components/radio-card-group/radio-card-group.test.tsx.snap
- packages/react/src/components/radio-card-group/radio-card.tsx
- packages/react/src/components/radio-card-group/styled-components.ts
- packages/storybook/stories/radio-card.stories.tsx
> fix(RadioCard): missing background change when radio is checked

- packages/react/src/components/radio-button-group/radio-button-group.tsx
https://github.com/user-attachments/assets/e720c811-2aa3-4964-8199-0e026a2311a0
> fix(RadioButtonGroup): fix collapse animation for React 18

- packages/react/src/components/icon/icon.tsx
- packages/storybook/stories/icon-library.mdx
Added missing icons pour la carte de /plan
https://equisoft.atlassian.net/browse/ABF-8860
> feat(Icons): added 2 icons

- packages/react/src/components/icon/icon.tsx
DS-1293
Ajouter l'icône "send" de feathers icon.
> feat(Icon): add send icon

- packages/react/src/components/date-picker/date-picker.test.tsx
- packages/react/src/components/date-picker/date-picker.tsx
https://issues.chromium.org/issues/393401475
https://equisoft.atlassian.net/browse/DS-1323
> fix(DatePicker): l'onglet de Chrome 133+ plante lors de l'ouverture du calendrier avec la souris

- packages/react/src/components/tabs/tabs.test.tsx.snap
- packages/react/src/components/tabs/tabs.tsx
update panelId de TabItem pour ne pas unmount
> fix(Tabs): update panelId de TabItem pour ne pas unmount

- packages/react/src/components/icon/icon.tsx
- packages/storybook/stories/icon-library.mdx
https://equisoft.atlassian.net/browse/DS-1366
> feat(Icons): add lock, unlock and uploadcloud icons to lib

- packages/react/src/components/dropdown-list/dropdown-list.test.tsx
- packages/react/src/components/dropdown-list/dropdown-list.tsx
- packages/storybook/stories/dropdown-list.stories.tsx
https://equisoft.atlassian.net/browse/DS-1367
> feat(DropdownList): add onClose event function

- packages/react/src/components/toggle-switch/toggle-switch.test.tsx
- packages/react/src/components/toggle-switch/toggle-switch.test.tsx.snap
- packages/react/src/components/toggle-switch/toggle-switch.tsx
https://equisoft.atlassian.net/browse/DS-1370
> feat(ToggleSwitch): allow label to be placed to the left of the toggle

- packages/react/src/components/dropdown-list/dropdown-list.test.tsx
- packages/react/src/components/dropdown-list/dropdown-list.test.tsx.snap
- packages/react/src/components/dropdown-list/dropdown-list.tsx
- packages/storybook/stories/3-changelog.mdx
This reverts commit d9e7206. This is not working correctly inside shadow dom.
> fix(Dropdown): revert - fix css z index issues with ReactPortal for Listbox

- packages/react/src/components/table/table.test.tsx.snap
- packages/react/src/components/table/table.tsx
fix textAlign property sur TableColumn
> fix(Table): fix textAlign property sur TableColumn

- packages/react/src/components/icon/icon.tsx
- packages/storybook/stories/icon-library.mdx
[DS-1375](https://equisoft.atlassian.net/browse/DS-1375)
[DS-1375]: https://equisoft.atlassian.net/browse/DS-1375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(Icon): add share-2 icon

- packages/react/src/components/tabs/tabs.test.tsx
- packages/react/src/components/tabs/tabs.tsx
- packages/storybook/stories/tabs.stories.tsx
[DS-1377](https://equisoft.atlassian.net/browse/DS-1377)
[DS-1377]: https://equisoft.atlassian.net/browse/DS-1377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(Tabs): add controlled mode for Tabs component

- packages/legacy-tests/src/components/combobox/combobox.test.tsx
- packages/react/package.json
- packages/react/src/components/combobox/combobox.test.tsx
- packages/react/src/components/combobox/combobox.tsx
- packages/storybook/stories/combobox.stories.tsx
- yarn.lock
[DS-1376](https://equisoft.atlassian.net/browse/DS-1376)
[DS-1376]: https://equisoft.atlassian.net/browse/DS-1376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(Combobox): display label instead of value when available
